authors = ["Margret Riegert <margret@eowyn.net>"]
description = "Syntax highlighting and LSP support for Crystal"
id = "crystal"
name = "Crystal"
repository = "https://github.com/crystal-lang-tools/zed-crystal"
schema_version = 1
version = "0.0.2"

[grammars.crystal]
commit = "cd3ae0751a58bca9fe875e580102578f5228a5a1"
repository = "https://github.com/crystal-lang-tools/tree-sitter-crystal"

[language_servers.crystalline]
language = "Crystal"
name = "crystalline"
