authors = ["Margret Riegert <margret@eowyn.net>"]
description = "Syntax highlighting and LSP support for Crystal"
id = "crystal"
name = "Crystal"
repository = "https://github.com/crystal-lang-tools/zed-crystal"
schema_version = 1
version = "0.0.1"

[grammars.crystal]
repository = "https://github.com/crystal-lang-tools/tree-sitter-crystal"
commit = "202da344c65a855fd9d31cfd51c46a20b2e9778d"

[language_servers.crystalline]
name = "crystalline"
language = "Crystal"
