authors = ["Margret Riegert <margret@eowyn.net>"]
description = "Syntax highlighting and LSP support for Crystal"
id = "crystal"
name = "Crystal"
repository = "https://github.com/crystal-lang-tools/zed-crystal"
schema_version = 1
version = "0.0.2"

[grammars.crystal]
commit = "3f5b4d3ee4956742c8ba609e3d5a0f4677d5c319"
repository = "https://github.com/crystal-lang-tools/tree-sitter-crystal"

[language_servers.crystalline]
language = "Crystal"
name = "crystalline"
