authors = ["Margret Riegert <margret@eowyn.net>"]
description = "Syntax highlighting for Crystal"
id = "crystal"
name = "Crystal"
repository = "https://github.com/nobodywasishere/zed-crystal"
schema_version = 1
version = "0.0.1"

[grammars.crystal]
commit = "61cc201c8eb3b6fd4d4eb3e0ac6c303a580eeb6b"
repository = "https://github.com/crystal-lang-tools/tree-sitter"
